### ISSUE TITLE
app crash with the message "JNI DETECTED ERROR IN APPLICATION: java_class == null"

### ISSUE THREAD

**Issue by EYALIN** [brody2consult/cordova-sqlite-storage#1005]
when running the prod app of android, the app crash when trying to open the DB (all Android versions):
```
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: java_class == null
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]     in call to GetMethodID
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]     from io.liteglue.g io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(java.lang.String, int)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470] "pool-1-thread-2" prio=5 tid=86 Runnable
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x131fa3a0 self=0x7f22120c00
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   | sysTid=24832 nice=0 cgrp=default sched=0/0 handle=0x7f21fff450
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 5638076 5149428 25 ) utm=0 stm=0 core=7 HZ=100
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   | stack=0x7f21efd000-0x7f21eff000 stackSize=1037KB
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #00 pc 00000000004cac88  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #01 pc 00000000004cac84  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #02 pc 000000000049d824  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #03 pc 00000000003240d8  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1164)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #04 pc 0000000000324488  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+188)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #05 pc 0000000000365cd8  /system/lib64/libart.so (_ZN3art3JNI11GetMethodIDEP7_JNIEnvP7_jclassPKcS6_+748)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #06 pc 0000000000029b20  /data/app/com.test.testapp-1/split_config.arm64_v8a.apk (???)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   native: #07 pc 00000000000759d0  /data/app/com.test.testapp-1/oat/arm64/base.odex (Java_io_liteglue_SQLiteNDKNativeDriver_sqlc_1db_1open__Ljava_lang_String_2I+156)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(Native method)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.liteglue.b.c(SourceFile:2)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.liteglue.f.<init>(SourceFile:4)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.liteglue.e.a(SourceFile:1)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.sqlc.b.i(SourceFile:1)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.sqlc.SQLitePlugin.n(SourceFile:6)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.sqlc.SQLitePlugin.e(SourceFile:1)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at io.sqlc.SQLitePlugin$d.run(SourceFile:1)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 16:09:24.761 24711 24832 F art     : art/runtime/java_vm_ext.cc:470]   at java.lang.Thread.run(Thread.java:762)
```

can someone help with this?
targetSdkVersion:31
minSdkVersion:19
Cordova:9.0.1
Ionic:6
Angular:14

**Comment by lordcoste** [comment]
Same here. It seems to happen when using Android App Bundle .aab. Any workaround?

**Comment by EYALIN** [comment]
@lordcoste my problem was related to proguard. when I removed it, it all works.

**Comment by toufiqpathan** [comment]
@EYALIN  thanks, yes problem was related to proguard , i have removed proguard plugin, and its working fine now
