### ISSUE TITLE
Cannot open DB after adding Crosswalk to project [ionic]

### ISSUE THREAD

**Issue by jkosmetos** [brody2consult/cordova-sqlite-storage#235]
Hey guys,

After adding crosswalk to my ionic project via `ionic browser add crosswalk@13.41.318.0`, I'm getting this error,

``` javascript
Error: Could not open database
    at newSQLError (SQLitePlugin.js:25)
    at SQLitePlugin.js:194
    at Object.cordova.callbackFromNative (cordova.js:288)
    at processMessage (cordova.js:1079)
    at processMessages (cordova.js:1102)
cordova.js:305 Error in Error callbackId: SQLitePlugin1197703998 : TypeError: undefined is not a function
```

 when trying to open the database like so,

``` javascript
window.sqlitePlugin.openDatabase({ name: 'myMobile.db' });
```

My cordova version: _4.3.0_
My cordova-android version: _4.0.0-dev_

Has the plugin been updated to support cordova-android 4.0?

Also, if you could shed some light on how I can give you more useful error information, I'd appreciate it!

Thanks!

**Comment by brody2consult** [comment]
I just tried running the spec test suite with cordova-android 4.0 (downloaded from https://github.com/apache/cordova-android/releases), and it ran with no problems. Maybe something went wrong in your environment. I can take a better look early next week.

**Comment by jkosmetos** [comment]
Thanks, much appreciated!

**Comment by jkosmetos** [comment]
I was able to recreate the problem on another machine, when creating a brand new Ionic project, my steps are as follows,

```
ionic start testApp tabs
cd testApp
ionic platform add android
cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git
```

I then altered the `www/js/app.js` file, and added,

``` javascript
$ionicPlatform.ready(function() {
    var db = window.sqlitePlugin.openDatabase({name: "my.db"});
});
```

and ran `ionic run android --device`, at this point it works, and I am able to open the DB without any issues, but as soon as I add crosswalk, something goes awry,

```
ionic browser add crosswalk
ionic run android --device
```

which produces the before mentioned error, and the below output from `adb logcat`,

```
D/AndroidChromeClient(18693): file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js: Line 171 : OPEN database: my.db
I/chromium(18693): [INFO:CONSOLE(171)] "OPEN database: my.db", source: file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js (171)
E/SQLitePlugin(18693): unexpected error, stopping db thread
E/SQLitePlugin(18693): com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Couldn't load sqlite4java-android-armv7l from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ionicframework.awsmapp346623-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ionicframework.awsmapp346623-2, /vendor/lib, /system/lib]]]: findLibrary returned null
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
E/SQLitePlugin(18693):  at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:235)
E/SQLitePlugin(18693):  at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:37)
E/SQLitePlugin(18693):  at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:652)
E/SQLitePlugin(18693):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SQLitePlugin(18693):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SQLitePlugin(18693):  at java.lang.Thread.run(Thread.java:841)
E/SQLitePlugin(18693): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load sqlite4java-android-armv7l from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ionicframework.awsmapp346623-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ionicframework.awsmapp346623-2, /vendor/lib, /system/lib]]]: findLibrary returned null
E/SQLitePlugin(18693):  at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/SQLitePlugin(18693):  at java.lang.System.loadLibrary(System.java:526)
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.Internal.tryLoadFromSystemPath(Internal.java:352)
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:124)
E/SQLitePlugin(18693):  at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
E/SQLitePlugin(18693):  ... 8 more
D/AndroidChromeClient(18693): file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js: Line 192 : OPEN database: my.db failed, aborting any pending transactions
I/chromium(18693): [INFO:CONSOLE(192)] "OPEN database: my.db failed, aborting any pending transactions", source: file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js (192)
D/AndroidChromeClient(18693): file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js: Line 79 : Could not open database
I/chromium(18693): [INFO:CONSOLE(79)] "Could not open database", source: file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js (79)
```

**Comment by ettiennelouw** [comment]
HI, also having the same issue!

**Comment by brody2consult** [comment]
Can you remove and then reinstall this plugin and report your results?

**Comment by jkosmetos** [comment]
I had already tried that, but I gave it another go, and I seem to be running into the same issue. 

My steps were as follows, 

`cordova plugin list`

which output the below

```
com.brodysoft.sqliteStorage 0.7.3 "Cordova sqlite storage"
com.ionic.keyboard 1.0.4 "Keyboard"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.crosswalk.engine 0.0.1-dev "Crosswalk Engine"
```

I then removed it and added it once more, as below,

```
cordova plugin remove com.brodysoft.sqliteStorage
cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git
```

While running the app on the device, and inspecting it via `chrome://inspect`, the below is logged in the console,

```
OPEN database: my.db SQLitePlugin.js:171
OPEN database: my.db failed, aborting any pending transactions SQLitePlugin.js:192
Could not open database SQLitePlugin.js:79
```

and logcat outputs,

```
D/AndroidChromeClient(19491): file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js: Line 171 : OPEN database: my.db
I/chromium(19491): [INFO:CONSOLE(171)] "OPEN database: my.db", source: file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js (171)
E/SQLitePlugin(19491): unexpected error, stopping db thread
E/SQLitePlugin(19491): com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Couldn't load sqlite4java-android-armv7l from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ionicframework.awsmapp346623-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ionicframework.awsmapp346623-2, /vendor/lib, /system/lib]]]: findLibrary returned null
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
E/SQLitePlugin(19491):  at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:235)
E/SQLitePlugin(19491):  at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:37)
E/SQLitePlugin(19491):  at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:652)
E/SQLitePlugin(19491):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SQLitePlugin(19491):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SQLitePlugin(19491):  at java.lang.Thread.run(Thread.java:841)
E/SQLitePlugin(19491): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load sqlite4java-android-armv7l from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ionicframework.awsmapp346623-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ionicframework.awsmapp346623-2, /vendor/lib, /system/lib]]]: findLibrary returned null
E/SQLitePlugin(19491):  at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/SQLitePlugin(19491):  at java.lang.System.loadLibrary(System.java:526)
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.Internal.tryLoadFromSystemPath(Internal.java:352)
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:124)
E/SQLitePlugin(19491):  at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
E/SQLitePlugin(19491):  ... 8 more
D/AndroidChromeClient(19491): file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js: Line 192 : OPEN database: my.db failed, aborting any pending transactions
I/chromium(19491): [INFO:CONSOLE(192)] "OPEN database: my.db failed, aborting any pending transactions", source: file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js (192)
D/AndroidChromeClient(19491): file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js: Line 79 : Could not open database
I/chromium(19491): [INFO:CONSOLE(79)] "Could not open database", source: file:///android_asset/www/plugins/com.brodysoft.sqliteStorage/www/SQLitePlugin.js (79)
```

**Comment by brody2consult** [comment]
I have tried the steps you gave me and am having trouble running it in my test environment. I will try it on another machine when I get a chance. But first, I suggest we try the plugin with Crosswalk but NOT with Ionic, with either of the following procedures:
- Crosswalk + Cordova under https://crosswalk-project.org/documentation/cordova.html
- https://crosswalk-project.org/documentation/embedding_crosswalk.html

I need to take care of another problem, will try this myself sometime later.

**Comment by jkosmetos** [comment]
No problem, I will give that a go and post my findings.

Thanks, would be much appreciated!

**Comment by brody2consult** [comment]
I just pushed some changes with an option for the Android version whether to use sqlite4java or the built-in Android database classes. Please let me know if the problem continues to persist if you use the `androidDatabaseImplementation: 2` in `sqlitePlugin.openDatabase()`, as described in README.md.

**Comment by jkosmetos** [comment]
I can confirm that adding `androidDatabaseImplementation: 2` to `sqlitePlugin.openDatabase()` resolves the matter, thank you!
