### ISSUE TITLE
Android 64 bit .so missing

### ISSUE THREAD

**Issue by rkg-mm** [brody2consult/cordova-sqlite-storage#242]
Hi,

we're currently testing our application on a Nexus 9 device, which has a 64-bit architecture.
There are currently no builds for 64-bit Android available, could you please add those?

The error is:
 unexpected error, stopping db thread
    com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/xxx-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsqlite4java-android-aarch64.so"

Thanks in advance!

**Comment by brody2consult** [comment]
That is a new target, different from the standard x86_64 target. As a workaround, you can use the androidDatabaseImplementation option as described in the readme.

**Comment by brody2consult** [comment]
I just pushed a new version with support for ARM-64 to: https://github.com/brodybits/Cordova-sqlite-storage-dev

Can you please report whether or not it works for you?

**Comment by obrmm** [comment]
Just tested it and it still does not work:

<ERROR MESSAGE>
04-21 09:56:12.064  20921-20982/xx.xxx E/art? No implementation found for java.lang.String com.almworks.sqlite4java._SQLiteSwiggedJNI.sqlite3_libversion() (tried Java_com_almworks_sqlite4java__1SQLiteSwiggedJNI_sqlite3_1libversion and Java_com_almworks_sqlite4java__1SQLiteSwiggedJNI_sqlite3_1libversion__)
04-21 09:56:12.067  20921-20982/xx.xxx E/SQLitePlugin? unexpected error, stopping db thread
    com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/xx.xxx-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsqlite4java-android-aarch64.so"
            at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
            at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
            at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
            at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.open(SQLitePlugin.java:375)
            at io.liteglue.SQLitePlugin.openDatabase(SQLitePlugin.java:223)
            at io.liteglue.SQLitePlugin.access$000(SQLitePlugin.java:37)
            at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:598)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xx.xxx-2/base.apk"],nativeLibraryDirectories=[/data/app/xx.xxx-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsqlite4java-android-aarch64.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.almworks.sqlite4java.Internal.tryLoadFromSystemPath(Internal.java:352)
            at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:124)
            at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
            at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
            at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
            at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.open(SQLitePlugin.java:375)
            at io.liteglue.SQLitePlugin.openDatabase(SQLitePlugin.java:223)
            at io.liteglue.SQLitePlugin.access$000(SQLitePlugin.java:37)
            at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:598)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
</ERROR MESSAGE>

**Comment by brody2consult** [comment]
My apologies: I forgot to include it in plugin.xml. Please pull again from the same repository and try it again.

**Comment by obrmm** [comment]
Still doesn't work.
The file is there under libs/arm/ but we still get a linker error. Is there possibly some wrong path anywhere?
The so file is searched in "/data/app/xx.xxx-1/lib/arm" but the files exists in "libs/arm".

**Comment by obrmm** [comment]
Sorry, my mistake...
The path in the generated apk is correct. but somehow the so file is not found

**Comment by brody2consult** [comment]
> Sorry, my mistake...

Nope, it was mine! You were right that libsqlite4java was searching under `lib/arm`-which also will need to be fixed. I just pushed another fix to `plugin.xml`. Can you try it yet again?

**Comment by obrmm** [comment]
No it was mine...
The libs directory in the project is libs/...
Only in the generated apk it's lib/...
Thus with your latest fix, the so files isn't compiled into the apk any more, which it was with the previous version...

**Comment by brody2consult** [comment]
> Thus with your latest fix, the so files isn't compiled into the apk any
> more, which it was with the previous version...

Latest fix withdrawn then. Unfortunately it appears that sqlite4java is searching the wrong path for the AMD-64 target. I will look if an easy fix may be possible..

**Comment by brody2consult** [comment]
I changed plugin.xml (in my dev version) to install the AMD64 version in the path as generated by Android NDK build. Can you (yet again) another try?

**Comment by obrmm** [comment]
Ok, seems to be working now.
We are getting no more error messages and the database is working.
Thanks a lot!

How long will it take until that fix is available in the stable release?

**Comment by brody2consult** [comment]
Very happy to hear, thanks for your help testing this one!

Give me 2-3 days. Ideally, I would like to get it working with x86_64 as well.

**Comment by obrmm** [comment]
Ok, thanks again!

**Comment by brody2consult** [comment]
The fix is now in the stable release. (I still have to test the x86_64 version when I get a chance.)

**Comment by brody2consult** [comment]
Tested with sqlite4android working on x86_64 ok.

**Comment by jchavarria1983** [comment]
hi I have a similar issue:

AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app-2/lib/arm64, /data/app/com.app-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsap.so"

Do you know how can i fix it ?
