### ISSUE TITLE
while installing 

### ISSUE THREAD

**Issue by shanmmukha1589** [brody2consult/cordova-sqlite-storage#325]
Repository "https://github.com/litehelpers/Cordova-sqlite-storage.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1440267840805/AUTHORS.md'
at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/om/.nvm/versions/v0.12.7/lib/node_modules/cordova/node_modules/q/q.js:749:13)

**Comment by BilelKrichen** [comment]
Just Run <code> npm install -g cordova@5.0.0 </code> then install your plugin 
<code> cordova plugin add cordova-sqlite-storage </code>

**Comment by brody2consult** [comment]
Looks like a problem with the Cordova tooling installation.
