### ISSUE TITLE
Can not install the plugin

### ISSUE THREAD

**Issue by NsAveek** [brody2consult/cordova-sqlite-storage#326]
cordova plugin add cordova-sqlite-storage

Fetching plugin "cordova-sqlite-storage" via plugin registry
npm http GET http://registry.cordova.io/cordova-sqlite-storage
npm http 404 http://registry.cordova.io/cordova-sqlite-storage
Error: 404 Not Found: cordova-sqlite-storage
    at RegClient.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\
lib\request.js:268:14)
    at Request.self.callback (C:\Users\User\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148
:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\cordo
va\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:1
4)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.
js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by nickblack647** [comment]
Did you fix this issue? I'm seeing this as well

**Comment by carolgit** [comment]
Is there a solution for it, already?
