### ISSUE TITLE
Can't install with plugman

### ISSUE THREAD

**Issue by screendriver** [brody2consult/cordova-sqlite-storage#364]
``` sh
$ cordova create foo
...
$ cd foo
$ cordova platform add android
...
$ plugman install --platform android --project . --plugin cordova-sqlite-storage
Fetching plugin "cordova-sqlite-storage" via npm
Installing "io.litehelpers.cordova.sqlite" for android
cordova version not detected (lacks script "/Users/me/Development/foo/cordova/version" ), continuing.
Failed to install 'io.litehelpers.cordova.sqlite':CordovaError: The provided path "/Users/me/Development/foo" is not an Android project.
    at new android_parser (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/cordova-lib/src/cordova/metadata/android_parser.js:35:15)
    at new PlatformProjectAdapter (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:61:19)
    at Object.getPlatformProject (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:97:23)
    at handleInstall (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:563:36)
    at /Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/q/q.js:749:13)
    at /Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/q/q.js:509:49
    at flush (/Users/me/.nvm/versions/node/v4.1.1/lib/node_modules/plugman/node_modules/q/q.js:108:17)
The provided path "/Users/me/Development/foo" is not an Android project.
$ cordova platform ls
Installed platforms: android 4.1.1
```

**Comment by brody2consult** [comment]
You cannot use plugman in a project that is created by the Cordova CLI. If you create a project using the Cordova CLI, then you add the plugin using the following command:

```
cordova plugin add cordova-sqlite-storage
```

You can also download the cordova-android distribution, use its bin/create command to create an Android-only project, then you can use `plugman install` to install the plugin in that project.

**Comment by screendriver** [comment]
`cordova plugin add cordova-sqlite-storage` did it. But in the [docs](https://github.com/litehelpers/Cordova-sqlite-storage#easy-install-with-plugman-tool) you say

```
NOTE: You can use cordova-sqlite-storage instead of https://github.com/litehelpers/Cordova-sqlite-storage to get an older, stable version.
```

Is it recommended to use plugman instead the "old" `cordova-sqlite-storage`?

**Comment by brody2consult** [comment]
The documentation in README.md needs some cleanup. In the past I found it easier to use the `plugman` solution for testing. But the Cordova CLI is much easier to use, and also much better documented. I would recommend using the Cordova CLI for most users.

**Comment by screendriver** [comment]
:+1:
