### ISSUE TITLE
Importing 16mb sql file error: "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by chauthai** [brody2consult/cordova-sqlite-storage#374]
Hi, 
I'm trying to import a 16 mb sql file and I'm getting this error. Is it related to the [sqlitePorter Plugin](https://github.com/dpa99c/cordova-sqlite-porter) or to Cordova-sqlite?

``` javascript
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at null.fn (file:///android_asset/www/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:75:22)
    at SQLitePluginTransaction.start (file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:283:12)
    at file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:144:32
```

**Comment by brody2consult** [comment]
According to https://github.com/dpa99c/cordova-sqlite-porter/issues/3#issuecomment-150203872 the issue is in the other plugin.
