### ISSUE TITLE
Suddenly stopped working on Android

### ISSUE THREAD

**Issue by rapidtechsolutions** [brody2consult/cordova-sqlite-storage#383]
Oddly stopped working on Android after updating to latest version;
## 

TypeError: Cannot read property 'openDatabase' of undefined
    at Object.openDB (file:///android_asset/www/lib/ngCordova/dist/ng-cordova.min.js:9:9674)
    at l.$scope.runopendownloads (file:///android_asset/www/js/controllers.js:770:42)
    at new <anonymous> (file:///android_asset/www/js/controllers.js:850:16)
    at e (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:67:315)
    at Object.instantiate (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:67:432)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:107:5
    at I.appendViewElement (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:385:3664)
    at Object.H.render (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:384:17369)
    at Object.H.init (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:384:16604)
    at I.render (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:385:2620)
##  <ion-nav-view name="menuContent" class="view-container" nav-view-transition="android">

No such issue on iOS. Android Device: Samsung Galaxy S5 Running Android 5.0

**Comment by brody2consult** [comment]
It is recommended to start with a fresh Ionic project with this plugin and start adding one thing at a time until you see when it stops working.
