### ISSUE TITLE
sqlite3_prepare_v2 failure on android

### ISSUE THREAD

**Issue by calebeaires** [brody2consult/cordova-sqlite-storage#393]
Infos:
1. CORDOVA VERSION: 5.4.1
2. Plugin version: 0.7.14
3. DB opened: database.db - OK
4. Android db implementation: sqlite4java (NDK)
5. database.db is on www folder.

```
ERROR: a statement error callback did not return false: sqlite3_prepare_v2 failure: no such table: bi
```

ADB LOGCAT

```
W/System.err(25787): java.sql.SQLException: sqlite3_prepare_v2 failure: no such table: bi
W/System.err(25787):    at io.liteglue.SQLiteGlueConnection.prepareStatement(SQLiteGlueConnection.java:46)
W/System.err(25787):    at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlStatementNDK(SQLitePlugin.java:443)
W/System.err(25787):    at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlBatch(SQLitePlugin.java:384)
W/System.err(25787):    at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:566)
W/System.err(25787):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(25787):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(25787):    at java.lang.Thread.run(Thread.java:818)
V/executeSqlBatch(25787): SQLitePlugin.executeSql[Batch](): Error=sqlite3_prepare_v2 failure: no such table: bi
I/chromium(25787): [INFO:CONSOLE(67)] "Erro na consulta: undefined", source: file:///android_asset/www/js/app.js (67)
I/chromium(25787): [INFO:CONSOLE(71)] "Erro na consulta: a statement error callback did not return false: sqlite3_prepare_v2 failure: no such table: bi", source: file:///android_asset/www/js/app.js (71)
```

**Comment by brody2consult** [comment]
For newer plugin version such as 0.7.14 the default Android implementation is actually using [liteglue / Android-sqlite-connector](https://github.com/liteglue/Android-sqlite-connector) (NDK). The error message indicates that your app tries to access a "bi" table that does not exist.

Issue #366 was already raised to improve the error reporting for Android. This is already fixed in
[litehelpers / Cordova-sqlite-enterprise-free](https://github.com/litehelpers/Cordova-sqlite-enterprise-free), which is available under a different licensing scheme.
