### ISSUE TITLE
Sqlite3.c not found when installing

### ISSUE THREAD

**Issue by Lloydyh** [brody2consult/cordova-sqlite-storage#505]
I've tried to resolve this with no luck so posting here.

I have created a new cordova project, iOS platform specific, which is done using the create command.

Plugins need to be installed using plugman, but when I do this I get the following error in terminal

```
Installing "cordova-sqlite-storage" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-sqlite-storage':Error: Uh oh!
"/Documents/R_n_D/sqliteTest/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!
    at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
    at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
    at installHelper (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/ios.js:54:16)
    at Object.module.exports.source-file.install (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/ios.js:106:13)
    at installWrapper (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:550:20)
    at /usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:347:24
    at _fulfilled (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:816:30)
Uh oh!
"/Documents/R_n_D/sqliteTest/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found!
```

Any thoughts? is it a bug? or do I need to do anything to the project before I install

Thanks

Lloyd

MacBook Pro
OS X El Capitan
Xcode Version 7.3.1
Latest iOS Cordova

**Comment by brody2consult** [comment]
It is already documented the use of plugman is no longer supported by this plugin. Evidently plugman does _not_ honor the installation hook that is needed to fetch the sqlite dependencies.

A new version at https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (available under GPL and commercial licensing options) will work with PhoneGap Build and _should_ work with plugman.

**Comment by Lloydyh** [comment]
Thanks for the quick response Chris
