### ISSUE TITLE
echoTest results in "Cannot perform this operation because there is no current transaction." error

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#706]
Just trying the plugin out. My test code so far is:

```			let sqlitePlugin : any = (<any>window).sqlitePlugin;
			if (sqlitePlugin == null) {
				console.log("!!!! SQLite plugin NOT found");
			} else {
				console.log("!!!! SQLite plugin found, running tests...");
				sqlitePlugin.echoTest(function() {
					console.log('ECHO test OK');
					sqlitePlugin.selfTest(
						() => { console.log('SELF test OK'); }
					);
				});
			}
```

All tests ran on latest Cordova
$ cordova -v
7.0.1

cordova-android@^6.2.3

Logcat of running it on Moto G running Android 4.4.4:
```I/chromium( 3600): [INFO:CONSOLE(26)] "!!!! SQLite plugin found, running tests...", source: file:///android_asset/www/app/Test.js (26)
I/chromium( 3600): [INFO:CONSOLE(28)] "ECHO test OK", source: file:///android_asset/www/app/Test.js (28)
I/chromium( 3600): [INFO:CONSOLE(175)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (175)
I/chromium( 3600): [INFO:CONSOLE(106)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (106)
V/SQLitePlugin( 3600): Android db implementation: built-in android.database.sqlite package
V/info    ( 3600): Open sqlite db: /data/data/com.myapp/databases/___$$$___litehelpers___$$$___test___$$$___.db
I/chromium( 3600): [INFO:CONSOLE(179)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (179)
W/System.err( 3600): java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
W/System.err( 3600):    at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
W/System.err( 3600):    at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
W/System.err( 3600):    at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
W/System.err( 3600):    at io.sqlc.SQLiteAndroidDatabase.executeSqlBatchStatement(SQLiteAndroidDatabase.java:258)
W/System.err( 3600):    at io.sqlc.SQLiteAndroidDatabase.executeSqlBatch(SQLiteAndroidDatabase.java:107)
W/System.err( 3600):    at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:340)
W/System.err( 3600):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 3600):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 3600):    at java.lang.Thread.run(Thread.java:841)
V/executeSqlBatch( 3600): SQLiteAndroidDatabase.executeSql[Batch](): Error=Cannot perform this operation because there is no current transaction.
I/chromium( 3600): [INFO:CONSOLE(136)] "cannot start next transaction: database not open", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (136)
I/chromium( 3600): [INFO:CONSOLE(175)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (175)
I/chromium( 3600): [INFO:CONSOLE(106)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (106)
I/chromium( 3600): [INFO:CONSOLE(179)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (179)
I/chromium( 3600): [INFO:CONSOLE(168)] "database already open: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (168)
```

Logcat of running it on a Doogee (yes, that's a brand...) phone running Android 6.0 and Chrome 44.0:
```07-05 11:16:55.668  8516  8516 I chromium: [INFO:CONSOLE(26)] "!!!! SQLite plugin found, running tests...", source: file:///android_asset/www/... (26)
07-05 11:16:55.675  8516  8516 I chromium: [INFO:CONSOLE(28)] "ECHO test OK", source: file:///android_asset/www/... (28)
07-05 11:16:55.680  8516  8516 I chromium: [INFO:CONSOLE(175)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (175)
07-05 11:16:55.682  8516  8516 I chromium: [INFO:CONSOLE(106)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (106)
07-05 11:16:55.683  8516  8567 V SQLitePlugin: Android db implementation: built-in android.database.sqlite package
07-05 11:16:55.685  8516  8607 V info    : Open sqlite db: /data/user/0/com.myapp/databases/___$$$___litehelpers___$$$___test___$$$___.db
07-05 11:16:55.712  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565536',true,1,["OK"],false);
07-05 11:16:55.764  8516  8516 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 179 : OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db - OK
07-05 11:16:55.764  8516  8516 I chromium: [INFO:CONSOLE(179)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (179)
07-05 11:16:55.783  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:55.784  8516  8607 W System.err: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
07-05 11:16:55.784  8516  8607 W System.err:    at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
07-05 11:16:55.784  8516  8607 W System.err:    at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
07-05 11:16:55.784  8516  8607 W System.err:    at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:542)
07-05 11:16:55.784  8516  8607 W System.err:    at io.sqlc.SQLiteAndroidDatabase.executeSqlBatchStatement(SQLiteAndroidDatabase.java:258)
07-05 11:16:55.784  8516  8607 W System.err:    at io.sqlc.SQLiteAndroidDatabase.executeSqlBatch(SQLiteAndroidDatabase.java:107)
07-05 11:16:55.784  8516  8607 W System.err:    at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:340)
07-05 11:16:55.784  8516  8607 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-05 11:16:55.784  8516  8607 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-05 11:16:55.784  8516  8607 W System.err:    at java.lang.Thread.run(Thread.java:818)
07-05 11:16:55.784  8516  8607 V executeSqlBatch: SQLiteAndroidDatabase.executeSql[Batch](): Error=Cannot perform this operation because there is no current transaction.
07-05 11:16:55.785  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565537',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"error","result":{"message":"Cannot perform this operation because there is no current transaction.","code":0}}]],false);
07-05 11:16:55.818  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:55.820  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565538',true,1,[[{"type":"success","result":{"rowsAffected":0}},{"type":"success","result":{"rows":[{"upperText":"TEST"}]}}]],false);
07-05 11:16:55.868  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:55.869  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565539',true,1,[[{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:55.879  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:55.880  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565540',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:55.885  8516  8516 I chromium: [INFO:CONSOLE(136)] "cannot start next transaction: database not open", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (136)
07-05 11:16:55.888  8516  8516 I chromium: [INFO:CONSOLE(175)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (175)
07-05 11:16:55.889  8516  8516 I chromium: [INFO:CONSOLE(106)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (106)
07-05 11:16:55.891  8516  8516 I chromium: [INFO:CONSOLE(179)] "OPEN database: ___$$$___litehelpers___$$$___test___$$$___.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (179)
07-05 11:16:55.894  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:55.894  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565542',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:55.912  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:55.913  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565543',true,1,[[{"type":"success","result":{"rowsAffected":0}},{"type":"success","result":{"rows":[{"myResult":""}]}}]],false);
07-05 11:16:55.918  8516  8516 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 168 : database already open: ___$$$___litehelpers___$$$___test___$$$___.db
07-05 11:16:55.918  8516  8516 I chromium: [INFO:CONSOLE(168)] "database already open: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (168)
07-05 11:16:55.919  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:55.920  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565544',true,1,[[{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:55.936  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:55.940  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565545',true,1,[[{"type":"success","result":{"rowsAffected":0}},{"type":"success","result":{}},{"type":"success","result":{"insertId":1,"rowsAffected":1}}]],false);
07-05 11:16:55.946  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:55.964  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565546',true,1,[[{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:55.979  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565547',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"success","result":{"rows":[{"id":1,"data":"test-value"}]}}]],false);
07-05 11:16:55.999  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:56.003  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565548',true,1,[[{"type":"success","result":{"rowsAffected":0}},{"type":"success","result":{"rowsAffected":1}}]],false);
07-05 11:16:56.037  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:56.049  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565549',true,1,[[{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:56.061  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565550',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"success","result":{"rows":[{"id":1,"data":"new-value"}]}}]],false);
07-05 11:16:56.074  8516  8607 D SQLiteDatabase: beginTransaction()
07-05 11:16:56.077  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565551',true,1,[[{"type":"success","result":{"rowsAffected":0}},{"type":"success","result":{"rowsAffected":1}},{"type":"success","result":{"insertId":2,"rowsAffected":1}}]],false);
07-05 11:16:56.081  8516  8607 D SQLiteDatabase: endTransaction()
07-05 11:16:56.110  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565552',true,1,[[{"type":"success","result":{"rowsAffected":0}}]],false);
07-05 11:16:56.117  8586  8586 I System.out: PM BuildConfig.DEBUG false
07-05 11:16:56.138  8586  8614 W System.err: should trigger true
07-05 11:16:56.684  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565554',true,1,[[{"type":"success","result":{"rows":[{"1":1}]}},{"type":"success","result":{"rows":[{"id":2,"data":123}]}}]],false);
07-05 11:16:56.701  8516  8516 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 223 : CLOSE database: ___$$$___litehelpers___$$$___test___$$$___.db
07-05 11:16:56.701  8516  8516 I chromium: [INFO:CONSOLE(223)] "CLOSE database: ___$$$___litehelpers___$$$___test___$$$___.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (223)
07-05 11:16:56.702  8516  8516 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 226 : closing db with transaction queue length: 0
07-05 11:16:56.703  8516  8516 I chromium: [INFO:CONSOLE(226)] "closing db with transaction queue length: 0", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (226)
07-05 11:16:56.703  8516  8516 D WebView : evaluateJavascript=cordova.callbackFromNative('SQLitePlugin1634565555',true,1,["OK"],false);
07-05 11:16:56.709  8516  8516 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 136 : cannot start next transaction: database not open
07-05 11:16:56.709  8516  8516 I chromium: [INFO:CONSOLE(136)] "cannot start next transaction: database not open", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (136)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase: Db file is deleted
07-05 11:16:56.716  8516  8567 D SQLiteDatabase: java.lang.Throwable: stacktrace
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.deleteDatabase(SQLiteDatabase.java:775)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.app.ContextImpl.deleteDatabase(ContextImpl.java:585)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.content.ContextWrapper.deleteDatabase(ContextWrapper.java:274)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at io.sqlc.SQLitePlugin.deleteDatabaseNow(SQLitePlugin.java:296)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at io.sqlc.SQLitePlugin.deleteDatabase(SQLitePlugin.java:276)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at io.sqlc.SQLitePlugin.executeAndPossiblyThrow(SQLitePlugin.java:107)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at io.sqlc.SQLitePlugin.execute(SQLitePlugin.java:66)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.os.Handler.dispatchMessage(Handler.java:111)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.os.Looper.loop(Looper.java:207)
07-05 11:16:56.716  8516  8567 D SQLiteDatabase:        at android.os.HandlerThread.run(HandlerThread.java:61)```

**Comment by brody2consult** [comment]
Sorry I missed this one. I never tried running selfTest directly in callback of echoTest, will try it when I get a chance.
