### ISSUE TITLE
keySet Error since last week

### ISSUE THREAD

**Issue by tgensol** [brody2consult/cordova-sqlite-storage#726]
Hi guys,

From the Android report of a new version, I am getting these since last week : 

> Appareil(s) présentant des problèmes
Sony Xperia XZ Premium (G8142) - Android 7.1
Huawei P8 Lite (hwALE-H) - Android 5.0
Google Pixel (sailfish) - Android 8.0
Google Pixel (sailfish) - Android 7.1
Huawei Mate 9 (HWMHA) - Android 7.0
Samsung Galaxy J1 Ace (j1acevelte) - Android 5.1

>Exceptions
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-oj.jar)
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
Crash with unknown cause detected. Please see logcat for details.
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)

I am using the 2.1.2 version, and the logcat of any of this device is saying :  

`java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
	at io.sqlc.SQLitePlugin.onDestroy(SQLitePlugin.java:157)
	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:297)
	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:480)
	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:315)
	at android.app.Activity.performDestroy(Activity.java:6926)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.support.test.runner.MonitoringInstrumentation.callActivityOnDestroy(MonitoringInstrumentation.java:637)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4286)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4317)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:466)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:420)
	at android.support.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:405)
	at android.support.test.espresso.action.KeyEventActionBase.waitForPendingForegroundAct`

I also got an huge % of crash of my users (from 99% to 80%). Do you know why and how to fix this one ? Should be linked to Java 8 or something ?

Best,

**Comment by brody2consult** [comment]
Thanks for reporting, this issue should be fixed in the latest version just published here and on npm.

Special thanks to @NeoLSN (Jason Yang/楊朝傑) for pointer to the solution in litehelpers/Cordova-sqlite-storage#727.
