### ISSUE TITLE
IllegalStateException when closing?

### ISSUE THREAD

**Issue by csabbey** [brody2consult/cordova-sqlite-storage#833]
I'm getting this stack trace for a crash through Crashlytics (and in the Play Store). Very naively, it looks like this plugin is trying to close a database that isn't open when the plugin is getting destroyed. 

```
Caused by java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
       at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:1053)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:528)
       at io.sqlc.SQLiteAndroidDatabase.closeDatabaseNow(SourceFile:83)
       at io.sqlc.SQLitePlugin.closeDatabaseNow(SourceFile:263)
       at io.sqlc.SQLitePlugin.onDestroy(SourceFile:167)
       at org.apache.cordova.PluginManager.onDestroy(SourceFile:297)
       at org.apache.cordova.CordovaWebViewImpl.handleDestroy(SourceFile:480)
       at org.apache.cordova.CordovaActivity.onDestroy(SourceFile:315)
       at android.app.Activity.performDestroy(Activity.java:6959)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4292)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4323)
       at android.app.ActivityThread.-wrap6(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6316)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
```

Is there something I might be doing that could cause this crash? It might just be noise, because it happens while the app is closing anyway, but I was worried this crash might block some other cleanup-on-destroy code from running.

**Comment by brody2consult** [comment]
<https://github.com/litehelpers/Cordova-sqlite-storage/blob/storage-master/src/android/io/sqlc/SQLiteAndroidDatabase.java#L83>

should be wrapped in a try/catch block to avoid this kind of a crash

In general I think more closeDatabaseNow code should be wrapped in try/catch to avoid this kind of a crash in the future. I hope to resolve this in an upcoming patch release.

The stack trace indicates to me that the database was opened with `androidDatabaseProvider: 'system'` (or `androidDatabaseImplementation: 2`) setting, I am curious why this was necessary. This kind of crash is **not** expected to happen if such a setting is not used.

I am also marking this as a **bug-data-loss-risk** issue since the built-in Android SQLite implementation is likely not built with `SQLITE_DEFAULT_SYNCHRONOUS=3` (EXTRA DURABLE build setting). SQLite database should be closed before the app exits to avoid possible corruption if the `SQLITE_DEFAULT_SYNCHRONOUS=3` setting is not used.as discussed in #736.

**Comment by csabbey** [comment]
> The stack trace indicates to me that the database was opened with androidDatabaseProvider: 'system' (or androidDatabaseImplementation: 2) setting, I am curious why this was necessary.

@brodybits  #601 is why - that's also me; I was losing inserts, maybe caused by having code in my own plugin reading from a database that I was inserting into with your plugin.

**Comment by brody2consult** [comment]
I just published a quick fix, should not happen any more. Thanks for reminding me about #601.

**Comment by brody2consult** [comment]
Hi @csabbey I just wanted to follow up if you still need to use `androidLockWorkaround: 1` to help work around the issues discussed in #601.

I would like to be able to remove this option if it is no longer needed by the user community. I raised #925 to discuss and would appreciate feedback there if you still need it for any reason.

I would suspect that this kind of a workaround should not be needed on recent, modern implementations of Android OS.
