### ISSUE TITLE
phonegap cannot build for ios

### ISSUE THREAD

**Issue by benag** [brody2consult/cordova-sqlite-storage#852]
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-sqlite-storage@^2.5.1" via npm Installing "cordova-sqlite-storage" at "2.6.0" for ios Error during processing of action! Attempting to revert... Failed to install 'cordova-sqlite-storage': CordovaError: Uh oh! "/private/tmp/gimlet/3448644/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found! at copyFile (/private/tmp/gimlet/3448644/project/cordova/lib/plugman/pluginHandlers.js:290:36) at copyNewFile (/private/tmp/gimlet/3448644/project/cordova/lib/plugman/pluginHandlers.js:322:5) at installHelper (/private/tmp/gimlet/3448644/project/cordova/lib/plugman/pluginHandlers.js:240:13) at install (/private/tmp/gimlet/3448644/project/cordova/lib/plugman/pluginHandlers.js:34:13) at ActionStack.process (/private/tmp/gimlet/3448644/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation (/private/tmp/gimlet/3448644/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20) at PluginManager.addPlugin (/private/tmp/gimlet/3448644/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17) at Api.addPlugin (/private/tmp/gimlet/3448644/project/cordova/Api.js:235:10) at handleInstall (/usr/local/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10) at /usr/local/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:364:24 Uh oh! "/private/tmp/gimlet/3448644/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/sqlite3.c" not found! - You can fix this here

**Comment by benag** [comment]
It also doesnt work for android on the phonegap build platform

**Comment by brody2consult** [comment]
The answer is that PhoneGap Build will not work with this plugin version since it depends on hook scripts, as I have already documented. The [`cordova-sqlite-evcore-extbuild-free`](https://www.npmjs.com/package/cordova-sqlite-evcore-extbuild-free) plugin version, which is available under GPL v3 and commercial license options, supports PhoneGap Build and includes major performance and stability enhancements for Android. For more details please see <https://xpbrew.consulting> or reach out to <sales@xpbrew.consulting>.
