### ISSUE TITLE
android.os.BinderProxy.finalize() timed out after 10 seconds errors

### ISSUE THREAD

**Issue by almothafar** [brody2consult/cordova-sqlite-storage#908]
So, I turned on crashlytics for my application and got reports that affect many users, the stack points to this plugin:

![image](https://user-images.githubusercontent.com/13887564/72738560-803a3980-3baa-11ea-97c0-24d494605922.png)

```
Fatal Exception: java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
       at android.view.ThreadedRenderer.nDeleteProxy(ThreadedRenderer.java)
       at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:413)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
       at java.lang.Thread.run(Thread.java:818)
........
pool-18-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:346)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

So the line causing this issue is: https://github.com/xpbrew/cordova-sqlite-storage/blob/dev/src/android/io/sqlc/SQLitePlugin.java#L346 

Any idea what the error is and how to get around it, I'm using Ionic with the latest version of this plugin which is `"cordova-sqlite-storage": "4.0.0",`

**Comment by brody2consult** [comment]
The following plugin versions are designed to avoid this kind of an issue with larger amounts of data, available under GPL v3 or commercial license terms:

- https://github.com/brodysoft/cordova-sqlite-evcore-extbuild-free
- https://github.com/brodysoft/cordova-plugin-sqlite-evplus-ext-common-free

Please see <https://xpbrew.consulting/> for more information.

**Comment by almothafar** [comment]
@brodybits so my issue is known and it is about the larger data than it should be? how much data I'm allowed for this plugin?

And for the other plugins, are they used as the same as this one? e.g. put and get data?

**Comment by brody2consult** [comment]
At this point I am not giving hard limits on this plugin version but here is what I can recall finding over the past few years:

- when inserting large amounts of data, it is OK up to 50K rows or so, up to about 100 bytes per row, troubles at 70K rows or so - solved in `cordova-sqlite-evcore-extbuild-free` and `cordova-plugin-sqlite-evplus-ext-common-free`
- known crash on Android on SELECT with large result sets, starting with 7K rows of about 100 bytes per row - solved in https://github.com/brodysoft/cordova-plugin-sqlite-evplus-ext-common-free

The thing is that I do not recall seeing the JVM TimeoutException before, so I really cannot promise without testing that any of the other plugins would directly resolve this particular issue. I will let you know if I can think of anything else you should try.

In case you are interested in high-priority commercial support please contact <sales@xpbrew.consulting> for more information.

API for storing and retrieving data is the same on all plugin versions discussed here.
